--- #YAML:1.0
name:               Text-Diff3
version:            0.07
abstract:           compute three-way differences between texts.
author:
    - MIZUTANI Tociyuki <tociyuki@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
